title: Anh (Andrew) Pham # your name (or website title) here

logo: "/image/IMG_1438.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  A Learner and A Traveler
  <br><br>
  <a href="https://www.linkedin.com/in/anhpham96/">LinkedIn</a> |
  <a href="https://github.com/apham15">GitHub</a> |
  <a href="/pdf/Anh Pham - DS.pdf">Resume</a>
  <p align="justify">
  I am pursing an MS degree in Business Analytics at Kellstadt Business School, DePaul University, where I hold the office of Vice President in th Kellstadt Business Analytics Organization.
  <br><br>
  I am currently a Data Scientist who loves applying Machine Learning Algorithms to bring insightful information for everyone
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
